[project]
name = "heart_rate"
version = "0.1.0"
description = "A simple heart rate calculation project"
authors = [{ name = "Fateme Hossaini" }]
requires-python = ">=3.7"
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"